name: Feature request
description: Propose a new feature or enhancement.
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Review the Single Source of Truth docs before filing: [Architecture](../../docs/ARCHITECTURE.md), [Codebase Overview](../../docs/CODEBASE_OVERVIEW.md), and [ADR index](../../docs/ADR/README.md).
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Describe what should be built in as much detail as you can
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Provide checklist items for success.
  - type: textarea
    id: notes
    attributes:
      label: Additional context
      description: Link to designs, spikes, or prior discussions.
