name: Block issues directory on main

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure issues/ is not in the merge diff
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1
          if git diff --name-only origin/${{ github.base_ref }}...HEAD | grep -E '^issues/'; then
            echo "::error::Remove issues/** files before merging; the agent CLI should clean them." >&2
            exit 1
          fi
